import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111114',
    margin: 0,
    padding: 0,
  },
  appBarContainer: {
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'white',
    padding: 0,
    margin: 0,
    height: 56,
  },
  appBar: {
    flex: 1,
    // backgroundColor: 'darkblue',
    borderColor: 'gray',
    borderWidth: StyleSheet.hairlineWidth,
    padding: 4,
    margin: 2,
    justifyContent: 'center',
  },
  displayContainer: {
    flex: 0.4,
    justifyContent: 'flex-start',
    // backgroundColor: 'red',
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'yellow',
    padding: 0,
    margin: 0,
  },
  buttonsContainer: {
    flex: 0.6,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    // backgroundColor: 'orange',
    padding: 0,
    margin: 0,
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'lightblue',
  },
  resultArea: {
    flex: 1,
    // backgroundColor: 'black',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    padding: 2,
    margin: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'lightblue',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  inputArea: {
    // flex: 0.3,
    height: 40,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    // backgroundColor: 'black',
    padding: 2,
    margin: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'lightgreen',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  displayLine: {
    margin: 2,
    padding: 2,
    flex: 1,
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'green',
  },
  displayOps: {
    margin: 0,
    padding: 0,
    width: 44,
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'green',
  },
  displayErase: {
    margin: 2,
    padding: 2,
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'gray',
  },
  displayEraseTouchable: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  displayResultContainer: {
    flexDirection: 'column',
    flex: 1,
  },
  displayResult: {
    margin: 2,
    padding: 2,
    flex: 1,
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    // borderWidth: StyleSheet.hairlineWidth,
    // borderColor: 'green',
  },
  displayButtons: {
    margin: 1,
    padding: 0,
    width: 40,
    height: 40,
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'teal',
    borderRadius: 20,
    // backgroundColor: 'teal'
  },
  padArea: {
    flex: 0.75,
    // backgroundColor: '#4756ff',
    padding: 2,
    margin: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'cyan',
  },
  opsArea: {
    flex: 0.25,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'magenta',
    // backgroundColor: 'magenta',
    padding: 2,
    margin: 2,
  },
  gridContainer: {
    flex: 1,
    borderColor: '#555555',
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  buttonContainer: {
    // width: "auto",
    // height: "auto",
    // borderRadius: 70 / 2,
    flex: 1,
    borderWidth: 0,
    borderColor: '#555555',
    backgroundColor: '#00111188',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderLeftWidth: StyleSheet.hairlineWidth,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  button: {},
  row: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-around',
  },
  textButton: {
    textAlign: 'center',
    fontSize: 40,
    color: 'darkgrey',
    fontFamily: 'sans-serif-light',
  },
  textButtonOp: {
    textAlign: 'center',
    fontSize: 56,
    color: 'gray',
    fontFamily: 'sans-serif-light',
  },
  viewPar: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  error: {
    position: 'absolute',
    margin: 2,
    padding: 2,
    bottom: 0,
    right: 0,
    height: 20,
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'cyan',
  },
  pasteError: {
    position: 'absolute',
    margin: 2,
    padding: 2,
    bottom: 0,
    left: 0,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: 'darkred',
  },
  textBar: {
    color: 'lightgray',
    fontSize: 20,
    fontFamily: 'sans-serif-light',
  },
  textDisplayLine: {
    color: 'white',
    fontSize: 32,
    textAlign: 'right',
    fontFamily: 'sans-serif-light',
  },
  textDisplayErase: {
    color: 'gray',
    fontSize: 32,
    textAlign: 'center',
    fontFamily: 'sans-serif-light',
  },
  textDisplayButtons: {
    color: 'teal',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'sans-serif-light',
  },
  textDisplayResult: {
    color: 'lightblue',
    textAlign: 'right',
    fontFamily: 'sans-serif-light',
  },
  textDisplayResultWarning: {
    color: 'lightblue',
    opacity: 0.6,
    textAlign: 'right',
    fontFamily: 'sans-serif-light',
  },
  textDisplayResultError: {
    color: 'gray',
    opacity: 0.6,
    textAlign: 'right',
    fontFamily: 'sans-serif-light',
  },
  textTicker: {
    fontFamily: 'sans-serif-light',
    color: 'teal',
    fontSize: 24,
    textAlign: 'center',
  },
  textError: {
    fontFamily: 'sans-serif-light',
    color: 'cyan',
    fontSize: 14,
    textAlign: 'right',
  },
  textPasteError: {
    fontFamily: 'sans-serif-light',
    color: '#cccccc',
    fontSize: 14,
    textAlign: 'left',
  },
})

export default styles
